-- Install all procedures
@procedures/gpa_mapping.sql
/
@procedures/proc_ExistUser.sql
/
@procedures/proc_checkLogin.sql
/
@procedures/proc_newStudent.sql
/
@procedures/proc_DropCourse.sql
/
@procedures/proc_viewCourseOfferings.sql
/
@procedures/proc_courseOfferingsForStudent.sql
/
@procedures/proc_viewCourses.sql
/
@procedures/proc_getProfileData.sql
/
@procedures/proc_EnrollCourse.sql
/
@procedures/proc_ApproveRequest.sql
/
@procedures/proc_CleanupRolls.sql
/
@procedures/proc_ViewWaitlistedCourses.sql
/
@procedures/proc_CleanupWaitlist.sql
/
@procedures/proc_CourseOfferingsInSemester.sql
/
@procedures/proc_EnterGrade.sql
/
@procedures/proc_GenerateBill.sql
/
@procedures/proc_GetUnityUserData.sql
/
@procedures/proc_getProfileData.sql
/
@procedures/proc_GPAForSem.sql
/
@procedures/proc_calcGPA.sql
/
@procedures/proc_MinCreditSatisfied.sql
/
@procedures/proc_NewCourse.sql
/
@procedures/proc_newCourseoffering.sql
/
@procedures/proc_NewSpPermReq.sql
/
@procedures/proc_newUser.sql
/
@procedures/proc_PayBill.sql
/
@procedures/proc_StudentsInCourse.sql
/
@procedures/proc_viewAllSemesters.sql
/
@procedures/proc_viewCourseOfferings.sql
/
@procedures/proc_ViewDepartments.sql
/
@procedures/proc_viewMyBill.sql
/
@procedures/proc_viewMyTranscript.sql
/
@procedures/proc_ViewPermRequests.sql
/
@procedures/proc_ViewSchedule.sql
/
@procedures/proc_ViewStudents.sql
/
@procedures/proc_ViewWaitlistedStudents.sql
/